name: Build
# this will work for every push
on: ["push"]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: '>=1.17.0'  

      - name: Build
        run: go build -v $(go list ./... | grep -v /example)

      - name: Test
        run: go test -v $(go list ./... | grep -v /example)